include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'example/**'
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
  plugins:
    - dart_code_metrics

dart_code_metrics:
  rules:
    - prefer-const-border-radius
    - avoid-border-all
    - prefer-correct-edge-insets-constructor
    - no-boolean-literal-compare
    - arguments-ordering:
        child-last: true

linter:
  rules:
    recursive_getters: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    avoid_print: true
    use_key_in_widget_constructors: true
    avoid_escaping_inner_quotes: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_brace_in_string_interps: true
    unnecessary_late: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    use_decorated_box: true
    use_function_type_syntax_for_parameters: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true