name: flutter_base_project
description: Flutter base project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  dartz: ^0.10.1

#  firebase_core: ^2.14.0
#  firebase_analytics: ^10.4.3
#  firebase_crashlytics: ^3.3.3
#  firebase_messaging: 14.6.4
#  firebase_remote_config: any
#
#  flutter_local_notifications: ^15.1.0+1

  intl: any

  flutter_riverpod: ^2.3.6

  dio: ^5.2.1+1

  shared_preferences: ^2.2.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  url_launcher: ^6.1.12
  analyzer: any
  shimmer: ^3.0.0

  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  build_runner: any
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  dart_code_metrics_presets: any
  dart_code_metrics: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Black.ttf
          style: normal